name: CI - Gradle Docker ECR

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t hello-java-app .
        docker tag hello-java-app:latest ${{ steps.login-ecr.outputs.registry }}/hello-java-app:latest

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/hello-java-app:latest
